apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gpd-deployment
  labels:
    app: gpd
spec:
  selector:
    matchLabels:
      app: gpd
  replicas: 2
  template:
    metadata:
      labels:
        app: gpd
    spec:
      containers:
      - name: grpc-python-test 
        image: k3nt/grpc-python-test 
        ports:
        - name: gpd-service
          containerPort: 50051 
---
apiVersion: v1
kind: Service
metadata:
  name: gpd-service
spec:
  selector:
    app: gpd
  ports:
  - port: 50051 
    nodePort: 30033
    targetPort: gpd-service 
  type: NodePort 
